from __future__ import annotations

import inspect
import json
import textwrap
from typing import Any

from . import fences, mdparse, repositories, udiff, unpacker
from .formats import FENCE_MACHINE_HEADER, FENCE_MANIFEST, MISSING_MANIFEST_ERROR

_SCRIPT_TEMPLATE = r"""
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
import warnings
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Generated by codecrate. Uses only the Python standard library.
# Supported pack format: __PACK_FORMAT_VERSION__

PACK_FORMAT_VERSION = "__PACK_FORMAT_VERSION__"
FENCE_MACHINE_HEADER = "__FENCE_MACHINE_HEADER__"
FENCE_MANIFEST = "__FENCE_MANIFEST__"
__MISSING_MANIFEST_ERROR_ASSIGNMENT__
DEFAULT_PACK_FILENAME = "__DEFAULT_PACK_FILENAME__"

_FENCE_OPEN_RE = re.compile(
    r"^(?P<fence>`{3,})[ \t]*(?P<info>[A-Za-z0-9_-]+)(?:[ \t]+.*)?$"
)
_MARK_RE = re.compile(r"FUNC:(?:v\d+:)?(?P<id>[0-9A-Fa-f]{8})")

__SHARED_RUNTIME__


def manifest_sha256(manifest: dict[str, Any]) -> str:
    canonical = json.dumps(
        manifest,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _verify_machine_header(
    machine_header: dict[str, Any] | None,
    manifest: dict[str, Any],
) -> None:
    if machine_header is None:
        raise ValueError(
            "Machine header check requested but no codecrate-machine-header block "
            "was found."
        )
    got_manifest_sha = str(machine_header.get("manifest_sha256") or "")
    if not got_manifest_sha:
        raise ValueError(
            "Machine header check requested but manifest_sha256 is missing."
        )
    exp_manifest_sha = manifest_sha256(manifest)
    if got_manifest_sha != exp_manifest_sha:
        raise ValueError(
            "Machine header checksum mismatch: "
            f"expected {exp_manifest_sha}, got {got_manifest_sha}"
        )


def _write_text_file(root: Path, rel: str, text: str) -> None:
    out_root = root.resolve()
    target = (out_root / rel).resolve()
    if out_root != target and out_root not in target.parents:
        raise ValueError(f"Refusing to write outside out_dir: {rel}")
    ensure_parent_dir(target)
    target.write_text(text, encoding="utf-8", newline="\n")


def _unpack_single_markdown(
    markdown_text: str,
    out_dir: Path,
    *,
    strict: bool,
    check_machine_header: bool,
) -> None:
    packed = parse_packed_markdown(markdown_text)
    manifest = packed.manifest
    if str(manifest.get("format") or "") != PACK_FORMAT_VERSION:
        raise ValueError(f"Unsupported format: {manifest.get('format')}")
    if check_machine_header:
        _verify_machine_header(packed.machine_header, manifest)

    missing: list[str] = []
    for item in manifest.get("files", []):
        if not isinstance(item, dict):
            raise ValueError("Manifest file entry must be an object.")
        rel = str(item.get("path") or "")
        if not rel:
            raise ValueError("Manifest file entry is missing a path.")
        stub = packed.stubbed_files.get(rel)
        exp = item.get("line_count")
        exp_n = int(exp) if exp is not None else None
        if stub is None or (exp_n and exp_n > 0 and not stub.strip()):
            missing.append(rel)
            continue

        marker_issues: list[str] = []
        reconstructed = _apply_canonical_into_stub(
            stub,
            list(item.get("defs") or []),
            packed.canonical_sources,
            strict=strict,
            issues=marker_issues,
        )
        reconstructed = normalize_newlines(reconstructed)
        if marker_issues:
            msg = (
                f"Unresolved marker mapping for {rel}: "
                + "; ".join(marker_issues[:5])
                + ("; ..." if len(marker_issues) > 5 else "")
            )
            warnings.warn(msg, RuntimeWarning, stacklevel=2)

        exp_sha = str(item.get("sha256_original") or "")
        if exp_sha:
            got_sha = hashlib.sha256(reconstructed.encode("utf-8")).hexdigest()
            if got_sha != exp_sha:
                warnings.warn(
                    f"SHA256 mismatch for {rel}: expected {exp_sha}, got {got_sha}",
                    RuntimeWarning,
                    stacklevel=2,
                )
        _write_text_file(out_dir, rel, reconstructed)

    if missing:
        files_str = ", ".join(missing[:10])
        if len(missing) > 10:
            files_str += "..."
        warnings.warn(
            f"Missing stubbed file blocks for {len(missing)} file(s): {files_str}",
            RuntimeWarning,
            stacklevel=2,
        )


def unpack_to_dir(
    markdown_text: str,
    out_dir: Path,
    *,
    strict: bool = False,
    check_machine_header: bool = False,
) -> None:
    sections = split_repository_sections(markdown_text)
    if not sections:
        _unpack_single_markdown(
            markdown_text,
            out_dir.resolve(),
            strict=strict,
            check_machine_header=check_machine_header,
        )
        return

    out_root = out_dir.resolve()
    for section in sections:
        _unpack_single_markdown(
            section.content,
            out_root / section.slug,
            strict=strict,
            check_machine_header=check_machine_header,
        )


def _default_pack_path() -> Path:
    return Path(__file__).resolve().with_name(DEFAULT_PACK_FILENAME)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Reconstruct files from a Codecrate pack using only the Python "
            "standard library."
        )
    )
    parser.add_argument(
        "pack_path",
        type=Path,
        nargs="?",
        default=None,
        help=f"Packed markdown file (default: sibling {DEFAULT_PACK_FILENAME})",
    )
    parser.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        required=True,
        help="Output directory for reconstructed files",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail when marker-based stub reconstruction cannot be fully resolved.",
    )
    parser.add_argument(
        "--check-machine-header",
        action="store_true",
        help="Verify the machine-header manifest checksum before writing files.",
    )
    args = parser.parse_args(argv)

    pack_path = args.pack_path or _default_pack_path()
    try:
        markdown_text = pack_path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        parser.exit(2, f"error: pack file not found: {pack_path}\n")
    except OSError as exc:
        parser.exit(2, f"error: failed to read {pack_path}: {exc}\n")

    try:
        unpack_to_dir(
            markdown_text,
            args.out_dir,
            strict=bool(args.strict),
            check_machine_header=bool(args.check_machine_header),
        )
    except ValueError as exc:
        parser.exit(2, f"error: {exc}\n")

    print(f"Unpacked into {args.out_dir}")


if __name__ == "__main__":
    main()
"""


def _wrap_string_chunks(value: str, *, width: int = 72) -> list[str]:
    words = value.split(" ")
    chunks: list[str] = []
    current = ""
    for index, word in enumerate(words):
        suffix = "" if index == len(words) - 1 else " "
        piece = word + suffix
        if not current:
            current = piece
            continue
        if len(current) + len(piece) <= width:
            current += piece
            continue
        chunks.append(current)
        current = piece
    if current:
        chunks.append(current)
    return chunks


def _render_wrapped_string_assignment(name: str, value: str) -> str:
    chunks = _wrap_string_chunks(value)
    if len(chunks) == 1:
        return f"{name} = {json.dumps(value)}"
    rendered_chunks = "".join(f"    {json.dumps(chunk)}\n" for chunk in chunks)
    return f"{name} = (\n{rendered_chunks})"


def _render_source(obj: Any) -> str:
    return textwrap.dedent(inspect.getsource(obj)).strip() + "\n\n"


def _shared_runtime_source() -> str:
    parts = [
        _render_source(udiff.normalize_newlines),
        _render_source(udiff.ensure_parent_dir),
        _render_source(fences.parse_fence_open),
        _render_source(fences.is_fence_close),
        _render_source(repositories.RepositorySection),
        _render_source(repositories.slugify_repo_label),
        _render_source(repositories._unique_slug),
        _render_source(repositories.split_repository_sections),
        _render_source(mdparse.PackedMarkdown),
        _render_source(mdparse._iter_fenced_blocks),
        _render_source(mdparse._section_bounds),
        _render_source(mdparse._parse_function_library),
        _render_source(mdparse._parse_stubbed_files),
        _render_source(mdparse.parse_packed_markdown),
        _render_source(unpacker._ws_len),
        _render_source(unpacker._apply_canonical_into_stub),
    ]
    return "".join(parts).rstrip()


def render_standalone_unpacker(
    *, pack_format_version: str, default_pack_filename: str
) -> str:
    rendered = (
        _SCRIPT_TEMPLATE.replace("__PACK_FORMAT_VERSION__", pack_format_version)
        .replace("__FENCE_MACHINE_HEADER__", FENCE_MACHINE_HEADER)
        .replace("__FENCE_MANIFEST__", FENCE_MANIFEST)
        .replace(
            "__MISSING_MANIFEST_ERROR_ASSIGNMENT__",
            _render_wrapped_string_assignment(
                "MISSING_MANIFEST_ERROR", MISSING_MANIFEST_ERROR
            ),
        )
        .replace("__DEFAULT_PACK_FILENAME__", default_pack_filename)
        .replace("__SHARED_RUNTIME__", _shared_runtime_source())
    )
    return textwrap.dedent(rendered).lstrip()
